---
title: "Air Pollution and Poverty Across Boroughs"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(stringr)
library(shiny)

```

```{r, include = F}
assign_pollutant <- function(vector) {
  if (str_detect(vector, "NOx"))
    pollutant_name = "NOx"
  else if (str_detect(vector, "PM2.5"))
    pollutant_name = "PM 2.5"
  else if (str_detect(vector, "SO2"))
    pollutant_name = "SO2"
  
  pollutant_name
}

poverty_df = readr::read_csv('./Data1/Poverty.csv') %>% 
  janitor::clean_names() %>% 
  filter(str_detect(geo_type_name, "UHF") == T) %>% 
  mutate(geography_id = as.integer(geography_id)) %>% 
  select(borough, geography_id, percent)

asthma_df = readr::read_csv('./Data1/nyc_asthma_cleaned.csv') %>% 
  filter(str_detect(geo_type_name, "UHF") == T) %>% 
  filter(str_detect(name, "Boiler") == T) %>% 
  mutate(pollutant = purrr::map(name, assign_pollutant)) %>% 
  rename(geography_id = geo_entity_id) %>% 
  inner_join(., poverty_df, by = "geography_id")
```



Column {.sidebar}
-----------------------------------------------------------------------

```{r, echo = F}
pollutants = c(asthma_df %>% distinct(pollutant) %>% pull())

# radioButtons widget - Pollutant
radioButtons("pollutant_choice", label = h3("Choose pollutant"), 
             choices = pollutants, selected = "NOx")
```

Column
----------------------------------------------------------------------

### Chart: Pollutant concentrations among NYC neighborhoods by poverty level

```{r, echo=F}
renderPlotly({
  asthma_df %>%
    filter(pollutant == input$pollutant_choice) %>% 
    plot_ly(x = ~percent, y = ~data_valuemessage, color = ~borough,
            type = "scatter", marker = list(size = 8),
            text = ~geo_entity_name) %>% 
    layout(xaxis = list(title = "Proportion of population in poverty (%)"),
           yaxis = list(title = "Pollutant concentration (Total emissions/km2)"))
})
```


rsconnect::setAccountInfo(name='wongus', token='CBD08B3DB1F2781D4B50438EB1A322C6', secret='P1YKMffhHKyqcaIhP5oUAhEliZNa0DhOpps5khK2')
library(rsconnect)
rsconnect::deployApp('./flex_2.Rmd')


